spring:
  datasource:
    # use druid as spring datasource pool
    type: com.alibaba.druid.pool.DruidDataSource
    # custom clickhouse datasource
    clickhouse:
      dbType: clickhouse
      driver: ru.yandex.clickhouse.ClickHouseDriver
      nodeList: localhost:8123,localhost:8123,localhost:8123
      database: bitmap_test
      username:
      password: 
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
    # druid configurations
    # see more details in https://github.com/alibaba/druid/wiki
    druid:
      # filters should be configured manually and set "enabled: true", default is "false"
      filters: stat
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      # web-console should be configured manually and set "enabled: true", default is "false"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      test-while-idle: false

task:
  execution:
    query:
      core-pool-size: 0
      max-pool-size: 500
      queue-capacity: 0
      keep-alive: 60
      rejected-policy: ABORT
      allow-core-thread-timeout: false
      thread-name-prefix: queryTask

query:
  timeout-millis: 10000


