server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
spring:
  application:
    name: clickhouse-learning-springboot
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  profiles:
    active: dev





