server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
spring:
  application:
    name: clickhouse-learning-mybatis
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    # use druid as spring datasource type
    type: com.alibaba.druid.pool.DruidDataSource
    # clickhouse jdbc params
    clickhouse:
      driver: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://localhost:8123/test
      username:
      password:
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
    # druid configurations
    # see more details in https://github.com/alibaba/druid/wiki
    druid:
      # filters should be configured manually and set "enabled: true", default is "false"
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      # web-console should be configured manually and set "enabled: true", default is "false"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
mybatis:
  type-aliases-package: person.rulo.clickhouse.learning.mybatis.entity
  mapper-locations: classpath:/mapper/*.xml